ALTER TABLE occurrence
    MODIFY COLUMN status ENUM('PENDENTE', 'APROVADA', 'EM_ANDAMENTO', 'ESPERANDO_PECA', 'FINALIZADO', 'CANCELADO') NOT NULL;

Alter TABLE order_service
    MODIFY  COLUMN status_service ENUM('PENDENTE', 'APROVADA', 'EM_ANDAMENTO', 'ESPERANDO_PECA', 'FINALIZADO', 'CANCELADO') NOT NULL;

