ALTER TABLE employee
    ADD COLUMN role ENUM(
    'MEDICO_ASSISTENTE', 'MEDICO_ESPECIALISTA', 'DIRETOR_CLINICO',
    'ENFERMEIRO_PADRAO', 'TECNICO_ENFERMAGEM', 'FISIOTERAPEUTA',
    'FARMACEUTICO', 'BIOMEDICO', 'RADIOLOGISTA', 'NUTRICIONISTA_CLINICO',
    'DIRETOR_ADMINISTRATIVO', 'GERENTE_RH', 'ANALISTA_ADMINISTRATIVO',
    'RECEPCIONISTA', 'AUXILIAR_ALMOXARIFADO', 'COORDENADOR_SLA',
    'SECRETARIO_EXECUTIVO', 'TECNICO_INFORMATICA', 'GESTOR_QUALIDADE',
    'DIRETOR_FINANCEIRO_CFO', 'ANALISTA_FATURAMENTO', 'AUDITOR_CONTABIL',
    'TESOUREIRO', 'ANALISTA_CONTAS_PAGAR_RECEBER', 'CONTADOR_HOSPITALAR',
    'GERENTE_COMPRAS_SUPRIMENTOS'
) NOT NULL DEFAULT 'RECEPCIONISTA';